list(APPEND XOLOTL_PERF_HEADERS
    ${XOLOTL_PERF_HEADER_DIR}/papi/PAPIHandler.h
    ${XOLOTL_PERF_HEADER_DIR}/papi/PAPIHardwareCounter.h
    ${XOLOTL_PERF_HEADER_DIR}/papi/PAPITimer.h
)

list(APPEND XOLOTL_PERF_SOURCES
    ${XOLOTL_PERF_SOURCE_DIR}/papi/PAPIHandler.cpp
    ${XOLOTL_PERF_SOURCE_DIR}/papi/PAPIHardwareCounter.cpp
    ${XOLOTL_PERF_SOURCE_DIR}/papi/PAPITimer.cpp
)
