#ifndef NE_CLUSTER_REACTION_NETWORK_H
#define NE_CLUSTER_REACTION_NETWORK_H

// Includes
//#include <xolotlPerf.h>
#include <string>
#include <vector>
#include <memory>
#include <map>
#include <unordered_map>
#include <ReactionNetwork.h>
#include <iostream>
#include <iomanip>
#include <algorithm>

namespace xolotlCore {

/**
 *  This class manages the set of reactants and compound reactants (
 *  combinations of normal reactants) for NE clusters. It also manages a
 *  set of properties that describes the total collection.
 *
 *  This class is a very heavyweight class that should not be abused.
 *
 *  Reactants that are added to this network must be added as with shared_ptrs.
 *  Furthermore, reactants that are added to this network have their ids set to
 *  a network specific id. Reactants should not be shared between separate
 *  instances of a NEClusterReactionNetwork.
 */
class NEClusterReactionNetwork: public ReactionNetwork {

private:

	/**
	 * Calculate the dissociation constant of the first cluster with respect to
	 * the single-species cluster of the same type based on the current clusters
	 * atomic volume, reaction rate constant, and binding energies.
	 *
	 * @param reaction The reaction
	 * @return The dissociation constant
	 */
	double calculateDissociationConstant(
			const DissociationReaction& reaction) const override;

	/**
	 * Calculate the binding energy for the dissociation cluster to emit the single
	 * and second cluster.
	 *
	 * @param reaction The reaction
	 * @return The binding energy corresponding to this dissociation
	 */
	virtual double computeBindingEnergy(
			const DissociationReaction& reaction) const override {
		double bindingEnergy = reaction.first.getFormationEnergy()
				+ reaction.second.getFormationEnergy()
				- reaction.dissociating.getFormationEnergy();

		return bindingEnergy;
	}

	/**
	 * Add the dissociation connectivity for the reverse reaction if it is allowed.
	 *
	 * @param emittingReactant The reactant that would emit the pair
	 * @param reaction The reaction we want to reverse
	 *
	 */
	void checkForDissociation(IReactant * emittingReactant,
			std::shared_ptr<ProductionReaction> reaction);

public:

	/**
	 * Default constructor, deleted to force construction using parameters.
	 */
	NEClusterReactionNetwork() = delete;

	/**
	 * The Constructor
	 *
	 * @param registry The performance handler registry
	 */
	NEClusterReactionNetwork(
			std::shared_ptr<xolotlPerf::IHandlerRegistry> registry);

	/**
	 * Copy constructor, deleted to prevent use.
	 */
	NEClusterReactionNetwork(const NEClusterReactionNetwork& other) = delete;

	/**
	 * Computes the full reaction connectivity matrix for this network.
	 */
	void createReactionConnectivity();

	/**
	 * This operation sets the temperature at which the reactants currently
	 * exists. It calls setTemperature() on each reactant.
	 *
	 * This is the simplest way to set the temperature for all reactants is to
	 * call the ReactionNetwork::setTemperature() operation.
	 *
	 * @param temp The new temperature
	 */
	virtual void setTemperature(double temp) override;

	/**
	 * This operation reinitializes the network.
	 *
	 * It computes the cluster Ids and network size from the allReactants vector.
	 */
	void reinitializeNetwork() override;

	/**
	 * This method redefines the connectivities for each cluster in the
	 * allReactans vector.
	 */
	void reinitializeConnectivities() override;

	/**
	 * This operation updates the concentrations for all reactants in the
	 * network from an array.
	 *
	 * @param concentrations The array of doubles that will be for the
	 * concentrations. This operation does NOT create, destroy or resize the
	 * array. Properly aligning the array in memory so that this operation
	 * does not overrun is up to the caller.
	 */
	void updateConcentrationsFromArray(double * concentrations) override;

	/**
	 * This operation returns the size or number of reactants and momentums in the network.
	 *
	 * @return The number of degrees of freedom
	 */
	virtual int getDOF() const override {
		return size() + getAll(ReactantType::NESuper).size() + 1;
	}

	/**
	 * This operation returns the list (vector) of each reactant in the network.
	 *
	 * @return The list of compositions
	 */
	virtual std::vector< std::vector <int> > getCompositionList() const override;

	/**
	 * Get the diagonal fill for the Jacobian, corresponding to the reactions.
	 *
	 * @param diagFill The pointer to the vector where the connectivity information is kept
	 */
	void getDiagonalFill(int *diagFill) override;

	/**
	 * Calculate all the rate constants for the reactions and dissociations of the network.
	 * Need to be called only when the temperature changes.
	 */
	void computeRateConstants() override;

	/**
	 * Compute the fluxes generated by all the reactions
	 * for all the clusters and their momentums.
	 *
	 * @param updatedConcOffset The pointer to the array of the concentration at the grid
	 * point where the fluxes are computed used to find the next solution
	 */
	void computeAllFluxes(double *updatedConcOffset) override;

    /**
     * Determine the number of partials for each cluster
     * and their starting locations within the vectors used
     * when computing partials.
     *
	 * @param size Number of partials for each cluster.
     * @param startingIdx Starting index of items owned by each reactant
     *      within the partials values array and the indices array.
     * @return Total number of partials for all clusters.
     */
	size_t initPartialsSizes(std::vector<int>& size,
                            std::vector<size_t>& startingIdx) const override;

    /**
     * Initialize the indexing used for computing partial derivatives
     * for all clusters and their momenta.
     *
	 * @param size Number of partials for each cluster.
     * @param startingIdx Starting index of items owned by each reactant
     *      within the partials values array and the indices array.
	 * @param indices The indices of the clusters for the partial derivatives.
     */
	void initPartialsIndices(const std::vector<int>& size,
                                    const std::vector<size_t>& startingIdx,
                                    std::vector<int>& indices) const override;

	/**
	 * Compute the partial derivatives generated by all the reactions
	 * for all the clusters and their momentum.
	 *
	 * @param size Number of partials for each cluster.
     * @param startingIdx Starting index of items owned by each reactant
     *      within the partials values array and the indices array.
	 * @param indices The indices of the clusters for the partial derivatives.
	 * @param vals The values of partials for the reactions
	 */
	void computeAllPartials(const std::vector<int>& size,
                                    const std::vector<size_t>& startingIdx,
                                    const std::vector<int>& indices,
                                    std::vector<double>& vals) const override;
};

}

#endif
