list(APPEND XOLOTL_CORE_HEADERS
    ${XOLOTL_CORE_HEADER_DIR}/reactants/detail/ReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/detail/ReSolutionReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/detail/SinkReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/AlloyClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/AlloyReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/AlloyReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/AlloyReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/AlloyTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/Cluster.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ClusterData.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/EnumSequence.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/FeClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/FeClusterGenerator.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/FeReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/FeReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/FeReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/FeTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/IReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/MemorySpace.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/NEClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/NEReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/NEReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/NEReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/NETraits.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/PSIClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/PSIClusterGenerator.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/PSIReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/PSIReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/PSIReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/PSITraits.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/Reaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/Reaction.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReactionCollection.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReactionData.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReactionNetworkTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReSolutionReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/ReSolutionReaction.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/SinkReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/SinkReaction.inl
    ${XOLOTL_CORE_HEADER_DIR}/reactants/SpeciesEnumSequence.h
    ${XOLOTL_CORE_HEADER_DIR}/reactants/TupleUtility.h
)
