list(APPEND XOLOTL_FACTORY_HEADERS
    ${XOLOTL_FACTORY_HEADER_DIR}/viz/VizHandlerRegistryFactory.h
)

list(APPEND XOLOTL_FACTORY_SOURCES
    ${XOLOTL_FACTORY_SOURCE_DIR}/viz/VizHandlerRegistryFactory.cpp
)
