list(APPEND XOLOTL_CORE_HEADERS
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ClusterData.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ClusterSet.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ConstantReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/NucleationReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/PSITrapMutation.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReactionCollection.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReactionData.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReactionUtility.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReSolutionReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/SinkReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/TransformReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/TrapMutationClusterData.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/TrapMutationHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/TrapMutationReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/TupleUtility.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyNetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/Cluster.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ConstantReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/EnumSequence.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeNetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeCrClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeCrNetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeCrReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeCrReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeCrTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/INetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/IPSIReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/IReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NENetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NETraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NucleationReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSINetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSITraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/Reaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReactionNetworkTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReSolutionReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/SinkReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/TransformReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/SpeciesEnumSequence.h
    ${XOLOTL_CORE_HEADER_DIR}/network/SpeciesId.h
    ${XOLOTL_CORE_HEADER_DIR}/network/TrapMutationReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ZrClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ZrNetworkHandler.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ZrReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ZrReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ZrTraits.h
)

list(APPEND XOLOTL_CORE_TPP_FILES
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/ClusterData.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/ConstantReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/NucleationReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/ReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/ReSolutionReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/SinkReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/TransformReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/TrapMutationClusterData.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/impl/TrapMutationReactionGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/AlloyClusterGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/AlloyReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/AlloyReactionNetwork.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/FeClusterGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/FeReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/FeReactionNetwork.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/FeCrClusterGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/FeCrReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/FeCrReactionNetwork.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/NEClusterGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/NEReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/NEReactionNetwork.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/NucleationReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/PSIClusterGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/PSIReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/PSIReactionNetwork.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/Reaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/ReactionNetwork.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/ReSolutionReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/SinkReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/TransformReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/TrapMutationReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/ZrClusterGenerator.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/ZrReaction.tpp
    ${XOLOTL_CORE_HEADER_DIR}/network/impl/ZrReactionNetwork.tpp
)

list(APPEND XOLOTL_CORE_SOURCES
    ${XOLOTL_CORE_SOURCE_DIR}/network/AlloyClusterGenerator.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/AlloyNetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/AlloyReactionNetwork.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/FeClusterGenerator.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/FeNetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/FeReactionNetwork.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/FeCrClusterGenerator.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/FeCrNetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/FeCrReactionNetwork.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/NEClusterGenerator.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/NENetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/NEReactionNetwork.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/NetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/PSINetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/ZrClusterGenerator.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/ZrNetworkHandler.cpp
    ${XOLOTL_CORE_SOURCE_DIR}/network/ZrReactionNetwork.cpp
)

if(NOT ${XOLOTL_INCLUDE_RN_TPP_FILES})
    list(APPEND XOLOTL_CORE_SOURCES
        ${XOLOTL_CORE_SOURCE_DIR}/network/PSIReactionNetworkFull.cpp
        ${XOLOTL_CORE_SOURCE_DIR}/network/PSIReactionNetworkHelium.cpp
        ${XOLOTL_CORE_SOURCE_DIR}/network/PSIReactionNetworkDeuterium.cpp
        ${XOLOTL_CORE_SOURCE_DIR}/network/PSIReactionNetworkTritium.cpp
    )
endif()
