list(APPEND XOLOTL_CORE_HEADERS
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/MemorySpace.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReactionCollection.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/ReSolutionReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/SinkReactionGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/detail/TupleUtility.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/AlloyTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/Cluster.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ClusterData.h
    ${XOLOTL_CORE_HEADER_DIR}/network/EnumSequence.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeClusterGenerator.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/FeReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/FeReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/FeTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/IReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/NEReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/NETraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIClusterGenerator.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIClusterGenerator.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/PSIReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/PSITraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/Reaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/Reaction.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/ReactionData.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReactionNetwork.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReactionNetwork.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/ReactionNetworkTraits.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReSolutionReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/ReSolutionReaction.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/SinkReaction.h
    ${XOLOTL_CORE_HEADER_DIR}/network/SinkReaction.inl
    ${XOLOTL_CORE_HEADER_DIR}/network/SpeciesEnumSequence.h
)
