#!/usr/bin/env python

import numpy as np
import math
import matplotlib.pyplot as plt
from   pylab import *

## Create two plots, one for the average density and one for the average diameter
fig1 = plt.figure()
denPlot = plt.subplot(311)
concPlot = plt.subplot(312)
diamPlot = plt.subplot(313)

## Open the data file generated by Xolotl (default is Alloy.dat)
time, vDen, vConc, vDiam, iDen, iConc, iDiam, = loadtxt('monitor.dat', usecols =
        (0,1,2,3,7,8,9), unpack=True) 

dose = time * 4.0e-7

## Density data
denPlot.plot(dose, iDen * 1.0e27, lw=8, ls='-', color=plt.cm.jet(100), alpha=0.7, label='I')
denPlot.plot(dose, vDen * 1.0e27, lw=4, ls='-', color=plt.cm.jet(180), alpha=0.7, label='V')

## Concentration data
concPlot.plot(dose, iConc * 1.0e27, lw=8, ls='-', color=plt.cm.jet(100), alpha=0.7, label='I')
concPlot.plot(dose, vConc * 1.0e27, lw=4, ls='-', color=plt.cm.jet(180), alpha=0.7, label='V')

## Diameter data
diamPlot.plot(dose, iDiam, lw=8, ls='-', color=plt.cm.jet(100), alpha=0.7, label='I')
diamPlot.plot(dose, vDiam, lw=4, ls='-', color=plt.cm.jet(180), alpha=0.7, label='V')

## Plot the legend
l = denPlot.legend(loc='best')
setp(l.get_texts(), fontsize=20)

## Some shaping
denPlot.set_xlabel("Dose (dpa)",fontsize=14)
denPlot.set_ylabel("Density (m-3)",fontsize=14)
denPlot.set_xlim([1.0e-6, 1.0e-2])
# denPlot.set_ylim([1.0e23, 8.0e23])
denPlot.set_xscale('log')
# denPlot.set_yscale('log')
denPlot.grid()
denPlot.tick_params(axis='both', which='major', labelsize=14)
denPlot.tick_params(axis='both', which='minor', labelsize=14)

concPlot.set_xlabel("Dose (dpa)",fontsize=14)
concPlot.set_ylabel("Concentration (m-3)",fontsize=14)
concPlot.set_xlim([1.0e-6, 1.0e-2])
# concPlot.set_ylim([1.0e23, 8.0e23])
concPlot.set_xscale('log')
# concPlot.set_yscale('log')
concPlot.grid()
concPlot.tick_params(axis='both', which='major', labelsize=14)
concPlot.tick_params(axis='both', which='minor', labelsize=14)

diamPlot.set_xlabel("Dose (dpa)",fontsize=14)
diamPlot.set_ylabel("Diameter (nm)",fontsize=14)
diamPlot.set_xlim([1.0e-6, 1.0e-2])
#diamPlot.set_ylim([0.0, 4.0])
diamPlot.set_xscale('log')
# diamPlot.set_yscale('log')
diamPlot.grid()
diamPlot.tick_params(axis='both', which='major', labelsize=14)
diamPlot.tick_params(axis='both', which='minor', labelsize=14)

## Show the plots
plt.show()
